services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        value: "your-telegram-bot-token-here"
      - key: ADMIN_ID
        value: "857216172"
      - key: WEBHOOK_URL
        value: "https://your-render-app-url.onrender.com/webhook"