services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: WEBHOOK_URL
        value: https://your-render-url.com/webhook
      - key: ADMIN_ID
        value: "857216172"  # or your Telegram ID as a string
